name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }} CI

    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade tox tox-gh-actions

      - name: Tox tests
        run: |
          tox -v

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          name: Python ${{ matrix.python-version }}
